-- An operator-facing task may contain one batch (one market) or several batches (multi-market).
create table redemption_code_tasks (
    id bigint generated by default as identity primary key,
    grouping_key varchar(140) not null unique,
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp
);

alter table redemption_code_batches add column task_id bigint;

-- Retain one task for every historic single batch and every historic multi-market export group.
insert into redemption_code_tasks (grouping_key, created_by, created_at)
select case when export_group_key is null then 'batch:' || cast(id as varchar)
            else 'group:' || export_group_key end,
       min(created_by),
       min(created_at)
from redemption_code_batches
group by case when export_group_key is null then 'batch:' || cast(id as varchar)
              else 'group:' || export_group_key end
order by min(created_at);

update redemption_code_batches batch
set task_id = (
    select task.id
    from redemption_code_tasks task
    where task.grouping_key = case when batch.export_group_key is null then 'batch:' || cast(batch.id as varchar)
                                   else 'group:' || batch.export_group_key end
);

alter table redemption_code_batches alter column task_id set not null;
alter table redemption_code_batches add constraint fk_redemption_batch_task
    foreign key (task_id) references redemption_code_tasks(id);
create index idx_redemption_code_batches_task_id
    on redemption_code_batches(task_id);
