create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(255) not null,
    display_name varchar(120) not null,
    enabled boolean not null default true,
    must_change_password boolean not null default false,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0
);

create table roles (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    name varchar(120) not null,
    description varchar(500)
);

create table permissions (
    id bigint generated by default as identity primary key,
    code varchar(100) not null unique,
    name varchar(120) not null
);

create table user_roles (
    user_id bigint not null references app_users(id) on delete cascade,
    role_id bigint not null references roles(id) on delete cascade,
    primary key (user_id, role_id)
);

create table role_permissions (
    role_id bigint not null references roles(id) on delete cascade,
    permission_id bigint not null references permissions(id) on delete cascade,
    primary key (role_id, permission_id)
);

create table operators (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(200) not null,
    operator_type varchar(20) not null default 'COMPANY',
    status varchar(20) not null default 'ACTIVE',
    contact_name varchar(120),
    contact_value varchar(200),
    remark text,
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0
);

create table user_operator_scopes (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id) on delete cascade,
    operator_id bigint references operators(id) on delete cascade,
    all_operators boolean not null default false,
    unique (user_id, operator_id)
);

create table operator_accounts (
    id bigint generated by default as identity primary key,
    operator_id bigint not null references operators(id),
    code varchar(50) not null,
    name varchar(120) not null,
    asset varchar(10) not null,
    network varchar(30),
    wallet_address varchar(200),
    start_date date,
    default_exchange_loss_rate numeric(12,8) not null default 0,
    default_exchange_loss_basis varchar(30) not null default 'TRANSFER',
    default_service_fee_rate numeric(12,8) not null default 0,
    default_service_fee_basis varchar(30) not null default 'SPEND',
    calculation_scale integer not null default 2,
    status varchar(20) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0,
    unique (operator_id, code),
    check (asset in ('USDT', 'USDC')),
    check (calculation_scale between 0 and 8),
    check (default_exchange_loss_rate between 0 and 1),
    check (default_service_fee_rate between 0 and 1)
);

create table daily_balances (
    id bigint generated by default as identity primary key,
    operator_account_id bigint not null references operator_accounts(id),
    business_date date not null,
    opening_balance numeric(24,8) not null default 0,
    suggested_opening_balance numeric(24,8),
    opening_mode varchar(20) not null default 'AUTO',
    opening_override_reason varchar(500),
    transfer_amount numeric(24,8) not null default 0,
    fraud_loss_amount numeric(24,8) not null default 0,
    fraud_deduction_source varchar(20),
    effective_transfer_amount numeric(24,8) not null default 0,
    spend_amount numeric(24,8) not null default 0,
    exchange_loss_rate numeric(12,8) not null default 0,
    exchange_loss_basis varchar(30) not null default 'TRANSFER',
    exchange_loss_auto_amount numeric(24,8) not null default 0,
    exchange_loss_amount numeric(24,8) not null default 0,
    exchange_loss_mode varchar(20) not null default 'AUTO',
    exchange_loss_override_reason varchar(500),
    service_fee_rate numeric(12,8) not null default 0,
    service_fee_basis varchar(30) not null default 'SPEND',
    service_fee_auto_amount numeric(24,8) not null default 0,
    service_fee_amount numeric(24,8) not null default 0,
    service_fee_mode varchar(20) not null default 'AUTO',
    service_fee_override_reason varchar(500),
    reflux_amount numeric(24,8) not null default 0,
    refund_amount numeric(24,8) not null default 0,
    other_deduction_amount numeric(24,8) not null default 0,
    other_reason varchar(500),
    closing_balance numeric(24,8) not null default 0,
    calculation_rule_version varchar(50) not null default 'BALANCE_V1_GROSS_TRANSFER',
    rounding_mode varchar(30) not null default 'HALF_UP',
    calculation_scale integer not null default 2,
    status varchar(20) not null default 'DRAFT',
    source_type varchar(20) not null default 'MANUAL',
    remark text,
    created_by bigint,
    updated_by bigint,
    confirmed_by bigint,
    confirmed_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0,
    unique (operator_account_id, business_date),
    check (transfer_amount >= 0 and fraud_loss_amount >= 0 and spend_amount >= 0),
    check (exchange_loss_amount >= 0 and service_fee_amount >= 0),
    check (reflux_amount >= 0 and refund_amount >= 0 and other_deduction_amount >= 0),
    check (exchange_loss_rate between 0 and 1 and service_fee_rate between 0 and 1),
    check (calculation_scale between 0 and 8)
);

create table accounting_period_locks (
    id bigint generated by default as identity primary key,
    operator_account_id bigint not null references operator_accounts(id),
    period_month date not null,
    status varchar(20) not null default 'LOCKED',
    locked_by bigint,
    locked_at timestamp with time zone,
    unlock_reason varchar(500),
    unlocked_by bigint,
    unlocked_at timestamp with time zone,
    row_version bigint not null default 0,
    unique (operator_account_id, period_month)
);

create table import_jobs (
    id bigint generated by default as identity primary key,
    source_type varchar(30) not null,
    original_filename varchar(500),
    file_sha256 varchar(64),
    status varchar(30) not null,
    conflict_strategy varchar(30) not null default 'SKIP_EXISTING',
    total_rows integer not null default 0,
    valid_rows integer not null default 0,
    warning_rows integer not null default 0,
    error_rows integer not null default 0,
    created_by bigint,
    committed_by bigint,
    committed_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table import_job_rows (
    id bigint generated by default as identity primary key,
    import_job_id bigint not null references import_jobs(id) on delete cascade,
    source_sheet varchar(200),
    source_row integer,
    source_json text,
    normalized_json text,
    operator_name varchar(200),
    operator_account_id bigint,
    business_date date,
    severity varchar(20) not null default 'OK',
    error_code varchar(100),
    error_message varchar(1000),
    action varchar(30),
    target_daily_balance_id bigint
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    actor_user_id bigint,
    action varchar(100) not null,
    entity_type varchar(100) not null,
    entity_id varchar(100),
    operator_id bigint,
    request_id varchar(100),
    ip_address varchar(100),
    reason varchar(500),
    before_json text,
    after_json text,
    created_at timestamp with time zone not null default current_timestamp
);

create index idx_daily_balances_account_date on daily_balances(operator_account_id, business_date desc);
create index idx_daily_balances_date_status on daily_balances(business_date, status);
create index idx_operator_accounts_operator_status on operator_accounts(operator_id, status);
create index idx_import_jobs_created_by_created_at on import_jobs(created_by, created_at desc);
create index idx_audit_logs_operator_created_at on audit_logs(operator_id, created_at desc);
create index idx_audit_logs_entity on audit_logs(entity_type, entity_id, created_at desc);
