create table redemption_campaigns (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    name varchar(200) not null,
    status varchar(20) not null default 'DRAFT',
    lookback_days integer not null default 7,
    description text,
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0,
    check (status in ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    check (lookback_days between 1 and 60)
);

create table redemption_campaign_tiers (
    id bigint generated by default as identity primary key,
    campaign_id bigint not null references redemption_campaigns(id),
    display_name varchar(120),
    min_deposit_amount numeric(24,8) not null,
    bonus_amount numeric(24,8) not null,
    sort_order integer not null default 0,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0,
    unique (campaign_id, min_deposit_amount),
    check (min_deposit_amount >= 0),
    check (bonus_amount >= 0)
);

create table redemption_code_issues (
    id bigint generated by default as identity primary key,
    campaign_id bigint not null references redemption_campaigns(id),
    campaign_tier_id bigint not null references redemption_campaign_tiers(id),
    claim_date date not null,
    deposit_window_start date not null,
    deposit_window_end date not null,
    tier_name varchar(120),
    min_deposit_amount numeric(24,8) not null,
    bonus_amount numeric(24,8) not null,
    redemption_code varchar(255) unique,
    remote_request_id varchar(80) not null unique,
    remote_reference_id varchar(255),
    state varchar(20) not null default 'PENDING',
    remote_error varchar(1000),
    generated_at timestamp with time zone,
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0,
    unique (campaign_id, campaign_tier_id, claim_date),
    check (state in ('PENDING', 'GENERATED', 'FAILED')),
    check (deposit_window_end >= deposit_window_start)
);

create index idx_redemption_issue_campaign_claim on redemption_code_issues(campaign_id, claim_date);
create index idx_redemption_tier_campaign_sort on redemption_campaign_tiers(campaign_id, sort_order);
