alter table redemption_campaign_tiers add column bonus_max_amount numeric(24,8);
update redemption_campaign_tiers set bonus_max_amount = bonus_amount where bonus_max_amount is null;
alter table redemption_campaign_tiers alter column bonus_max_amount set not null;

alter table redemption_code_issues add column bonus_max_amount numeric(24,8);
update redemption_code_issues set bonus_max_amount = bonus_amount where bonus_max_amount is null;
alter table redemption_code_issues alter column bonus_max_amount set not null;

create table redemption_code_batches (
    id bigint generated by default as identity primary key,
    campaign_id bigint not null references redemption_campaigns(id),
    claim_date_from date not null,
    claim_date_to date not null,
    lookback_days integer not null,
    expected_code_count integer not null,
    status varchar(30) not null default 'CREATING',
    published_by bigint,
    published_at timestamp with time zone,
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0,
    check (claim_date_to >= claim_date_from),
    check (lookback_days between 1 and 60),
    check (expected_code_count > 0),
    check (status in ('CREATING', 'READY_TO_PUBLISH', 'PUBLISHED', 'COMPLETED'))
);

alter table redemption_code_issues add column batch_id bigint references redemption_code_batches(id);
alter table redemption_code_issues add column workflow_status varchar(30) not null default 'PENDING_CREATION';
alter table redemption_code_issues add column remote_configuration_id varchar(255);
alter table redemption_code_issues add constraint chk_redemption_issue_workflow_status
    check (workflow_status in ('PENDING_CREATION', 'CREATED', 'PUBLISHED', 'CODE_IMPORTED', 'FAILED'));

create unique index uq_redemption_issue_remote_configuration on redemption_code_issues(remote_configuration_id);
create index idx_redemption_batch_campaign_created on redemption_code_batches(campaign_id, created_at desc);
create index idx_redemption_issue_batch on redemption_code_issues(batch_id, claim_date, campaign_tier_id);
