create table redemption_remote_connections (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name varchar(120) not null,
    base_url varchar(500) not null,
    bearer_token_ciphertext text not null,
    publish_environment varchar(20) not null default 'test',
    flow_times integer not null default 5,
    key_number integer not null default 1,
    single_user_limit integer not null default 1,
    single_key_limit integer not null default 2000,
    require_bind_bank_card boolean not null default false,
    require_bind_phone boolean not null default true,
    check_uuid boolean not null default true,
    uuid_reward_limit integer not null default 1,
    check_login_ip boolean not null default true,
    login_ip_reward_limit integer not null default 1,
    check_register_ip boolean not null default true,
    register_ip_reward_limit integer not null default 1,
    enabled boolean not null default true,
    last_checked_at timestamp with time zone,
    last_error varchar(1000),
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0,
    check (publish_environment in ('test', 'prod')),
    check (flow_times >= 0),
    check (key_number = 1),
    check (single_user_limit >= 1),
    check (single_key_limit >= 1),
    check (uuid_reward_limit >= 1),
    check (login_ip_reward_limit >= 1),
    check (register_ip_reward_limit >= 1)
);

alter table redemption_code_batches add column remote_connection_id bigint references redemption_remote_connections(id);
alter table redemption_code_batches add column remote_publish_task_id varchar(255);

alter table redemption_code_issues add column remote_group_key varchar(255);
alter table redemption_code_issues add column remote_label_ids_json text;

alter table redemption_code_issues drop constraint chk_redemption_issue_workflow_status;
alter table redemption_code_issues add constraint chk_redemption_issue_workflow_status
    check (workflow_status in ('PENDING_CREATION', 'CREATING_REMOTE', 'CREATED', 'PUBLISHED', 'CODE_IMPORTED', 'FAILED'));

create index idx_redemption_batch_remote_connection on redemption_code_batches(remote_connection_id, created_at desc);
