create table redemption_remote_markets (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name varchar(120) not null,
    base_url varchar(500) not null,
    enabled boolean not null default true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    row_version bigint not null default 0
);

-- Existing accounts remain usable after the split: each is assigned a private migrated market.
insert into redemption_remote_markets (code, name, base_url, enabled, created_by, updated_by, created_at, updated_at)
select 'MKT_' || id, left(name, 100) || '（迁移盘口）', base_url, enabled, created_by, updated_by, created_at, updated_at
from redemption_remote_connections;

alter table redemption_remote_connections add column market_id bigint;
update redemption_remote_connections connection
set market_id = market.id
from redemption_remote_markets market
where market.code = 'MKT_' || connection.id;
alter table redemption_remote_connections alter column market_id set not null;
alter table redemption_remote_connections add constraint fk_redemption_remote_connection_market
    foreign key (market_id) references redemption_remote_markets(id);

create index idx_redemption_remote_connection_market on redemption_remote_connections(market_id, enabled, name);
